"""Video pipeline constants — single source of truth for all magic numbers."""

VIDEO_SIZE = (1280, 720)
SCENE_DURATION_DEFAULT = 7
SCENE_DURATION_MIN = 4
SCENE_DURATION_MAX = 30
AUDIO_PADDING_SECONDS = 1.0
MAX_SCENES = 10
MAX_BULLETS = 3
MAX_BULLET_CHARS = 48
MAX_EXPANSION_SCENES = max(2, MAX_SCENES - 3)
MAX_KEYWORDS = 4
TRANSITION_SECONDS = 0.35
VIDEO_FPS = 24
NARRATION_MAX_CHARS = 280
MAX_NODE_DESC_CHARS = 30
MAX_SUBTITLE_CHARS = 160
